query getAlbums($page: Int!, $size: Int!) {
  albums(options: { paginate: { page: $page, limit: $size } }) {
    data {
      id
      title
      user {
        id
        name
      }
      photos {
        data {
          id
        }
      }
    }
    meta {
      totalCount
    }
  }
}

mutation deleteAlbum($id: ID!) {
  deleteAlbum(id: $id)
}
