query getAlbumFull($id: ID!, $page: Int!, $size: Int!) {
  album(id: $id) {
    id
    title
    user {
      id
      name
      username
    }
    photos(options: { paginate: { page: $page, limit: $size } }) {
      data {
        id
        title
        url
        thumbnailUrl
      }
      meta {
        totalCount
      }
    }
  }
}
